# Generated by Django 6.0.3 on 2026-03-21 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='watch',
            field=models.BooleanField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_comments', to='auctions.auction_listing'),
        ),
    ]
