# Generated by Django 6.0.3 on 2026-03-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_listing_watch_alter_comment_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='img',
            field=models.ImageField(blank=True, upload_to='listings/'),
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='watch',
            field=models.BooleanField(default=False),
        ),
    ]
