# Generated by Django 6.0.3 on 2026-04-03 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auction_listing_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='category',
            field=models.CharField(choices=[('FR', 'Fashion'), ('TY', 'Toys'), ('AR', 'Artifact'), ('JW', 'Jewelry'), ('MC', 'Machinary')], max_length=2),
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listing_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='watch',
            field=models.ManyToManyField(related_name='user_watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
